Add files via upload: Upload logo CFB and tokens information
BuildOnViction/tokens pull request #400
Opened 2023-10-31 00:51 UTC by cryptocfb

2023-11-12 08:21 UTC, bobcoin98 commented
Please change filenames to lowercase format
(This content is created via [Gittool](https://github.com/thanhnguyennguyen/lazy/tree/master/git)) 
 On behalf of [bobcoin98](https://github.com/bobcoin98)

2023-11-12 09:09 UTC, cryptocfb commented
> Please change filenames to lowercase format (This content is created via [Gittool](https://github.com/thanhnguyennguyen/lazy/tree/master/git)) On behalf of [bobcoin98](https://github.com/bobcoin98)
filename is lowercase format, why need change?
What filenames of ? Logo or token name? of something else? i do not understand what you mean?

2023-11-12 09:22 UTC, bobcoin98 requested changes
Please follow  this 
https://github.com/BuildOnViction/tokens#2-create-a-pull-request

2023-11-12 09:25 UTC, cryptocfb commented
> Please follow this https://github.com/BuildOnViction/tokens#2-create-a-pull-request

Yes, we have update logo filename to lowercase here : https://drive.google.com/file/d/1buOD_Op_WPbtPEEe9qV8UBRS7og4XRyG/view?usp=sharing

2023-11-12 09:27 UTC, bobcoin98 commented
![image](https://github.com/BuildOnViction/tokens/assets/138571486/60534b86-8395-4ed4-9ec1-04d14b56e2b0)

2023-11-12 09:27 UTC, bobcoin98 commented
`B93` ????

2023-11-12 09:30 UTC, bobcoin98 requested changes
please update .png filename as weel

2023-11-12 09:34 UTC, cryptocfb commented
> please update .png filename as well

Where to update again? can not edit file png again? where to publish again?
Our error because of your copy on https://tomoscan.io/token/0x567b1e373f7285e9a32f5eeb9305b6964b6a3532
when we copy smc it auto change to B from b, please fix it 
But now, how to rename .png file?
i can not edit that png file

2023-11-12 09:37 UTC, bobcoin98 commented
update filename same you did with json file

2023-11-12 11:18 UTC, cryptocfb commented
[0x567b1e373f7285e9a32f5eeb9305b6964b6a3532.json](https://github.com/BuildOnViction/tokens/files/13327815/0x567b1e373f7285e9a32f5eeb9305b6964b6a3532.json)
![0x567b1e373f7285e9a32f5eeb9305b6964b6a3532](https://github.com/BuildOnViction/tokens/assets/149397002/37aa3bc0-f1f0-4641-b15c-887baa0864c9)

2023-11-12 11:19 UTC, cryptocfb commented
https://drive.google.com/file/d/13Y_Foyz-n84w9aV65LpzhqxZTz3_ZWsQ/view?usp=sharing
https://drive.google.com/file/d/1QtaM0C-xsvepBuZejNT0nhwr9jJlXTGP/view?usp=sharing

2023-11-12 11:22 UTC, cryptocfb reviewed
![0x567b1e373f7285e9a32f5eeb9305b6964b6a3532](https://github.com/BuildOnViction/tokens/assets/149397002/e5c97797-3de2-42fb-88b2-177addfffecd)

2023-11-12 11:28 UTC, cryptocfb reviewed
![0x567b1e373f7285e9a32f5eeb9305b6964b6a3532](https://github.com/BuildOnViction/tokens/assets/149397002/e84dd9a6-077a-46b0-9e53-9779d6079498)

2023-11-12 11:35 UTC, cryptocfb reviewed
[0x567b1e373f7285e9a32f5eeb9305b6964b6a3532.json](https://github.com/BuildOnViction/tokens/files/13327853/0x567b1e373f7285e9a32f5eeb9305b6964b6a3532.json)

2023-11-12 12:00 UTC, cryptocfb commented
https://github.com/tomochain/tokens/issues/401

2023-11-12 12:29 UTC, cryptocfb commented
File has been updated, please promptly upload the CFB logo to the Tomo
blockchain network. (
https://github.com/BuildOnViction/tokens/pull/400/commits/271ccf01891624b25c338af508d57baa35b2c5f4).
Thank you.

Vào CN, 12 thg 11, 2023 vào lúc 16:37 Bob Jr ***@***.***>
đã viết:

> update filename same you did with json file
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BuildOnViction/tokens/pull/400#issuecomment-1807072070>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDTZ4CVBC7TJYDFWVBLP5NLYECKFLAVCNFSM6AAAAAA6W4AMX6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBXGA3TEMBXGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-13 01:47 UTC, cryptocfb commented
> update filename same you did with json file

Done, pls update logo for us on Tomo(Vic) Wallet, C98 Wallet and Tomoscan.
Thanks

2023-11-13 02:27 UTC, bobcoin98 commented
Rule violation
 - Number of files: only 2 file changes accepted 
 Logo size: 256x256  ( 512x512 detected)
(This content is created via [Gittool](https://github.com/thanhnguyennguyen/lazy/tree/master/git)) 
 On behalf of [bobcoin98](https://github.com/bobcoin98)

2023-11-13 03:14 UTC, bobcoin98 requested changes
follow steps here : https://github.com/BuildOnViction/tokens#2-create-a-pull-request

[2. Create a pull request](https://github.com/BuildOnViction/tokens/pull/400/files#2-create-a-pull-request)

[Image Requirements](https://github.com/BuildOnViction/tokens/pull/400/files#image-requirements)

file extension: png (PNG is invalid)
name：contract_address.png (filename in lowercase). Example: 0xea8d13af16a33fc5de19c0b1edcf4cd053bd2fa9.png
Resolution: recommend 256x256 px
size: under 512 KB
background: preferably transparent
(use simple drag and drop online service [tinypng](https://tinypng.com/) to optimize image size)

[Token Information Requirement](https://github.com/BuildOnViction/tokens/pull/400/files#token-information-requirement)

file extension: json (JSON is invalid)
name：contract_address.json (filename in lowercase). Example: 0xea8d13af16a33fc5de19c0b1edcf4cd053bd2fa9.json
required fields: symbol, name, website

2023-11-13 04:30 UTC, cryptocfb commented
> follow steps here : https://github.com/BuildOnViction/tokens#2-create-a-pull-request
> 
> [2. Create a pull request](https://github.com/BuildOnViction/tokens/pull/400/files#2-create-a-pull-request)
> 
> [Image Requirements](https://github.com/BuildOnViction/tokens/pull/400/files#image-requirements)
> 
> file extension: png (PNG is invalid) name：contract_address.png (filename in lowercase). Example: 0xea8d13af16a33fc5de19c0b1edcf4cd053bd2fa9.png Resolution: recommend 256x256 px size: under 512 KB background: preferably transparent (use simple drag and drop online service [tinypng](https://tinypng.com/) to optimize image size)
> 
> [Token Information Requirement](https://github.com/BuildOnViction/tokens/pull/400/files#token-information-requirement)
> 
> file extension: json (JSON is invalid) name：contract_address.json (filename in lowercase). Example: 0xea8d13af16a33fc5de19c0b1edcf4cd053bd2fa9.json required fields: symbol, name, website

I want delete all and upload all files again? how to do that? I can not delete pgn file, show me, thanks

2023-11-13 04:35 UTC, cryptocfb commented
I want delete all and upload all files again? how to do that? I can not delete pgn file, show me, thanks, it do not show delete files
![cfb](https://github.com/BuildOnViction/tokens/assets/149397002/26246402-9d48-4172-abdc-fae1e1840b32)

2023-11-13 07:28 UTC, cryptocfb commented
> follow steps here : https://github.com/BuildOnViction/tokens#2-create-a-pull-request
> 
> [2. Create a pull request](https://github.com/BuildOnViction/tokens/pull/400/files#2-create-a-pull-request)
> 
> [Image Requirements](https://github.com/BuildOnViction/tokens/pull/400/files#image-requirements)
> 
> file extension: png (PNG is invalid) name：contract_address.png (filename in lowercase). Example: 0xea8d13af16a33fc5de19c0b1edcf4cd053bd2fa9.png Resolution: recommend 256x256 px size: under 512 KB background: preferably transparent (use simple drag and drop online service [tinypng](https://tinypng.com/) to optimize image size)
> 
> [Token Information Requirement](https://github.com/BuildOnViction/tokens/pull/400/files#token-information-requirement)
> 
> file extension: json (JSON is invalid) name：contract_address.json (filename in lowercase). Example: 0xea8d13af16a33fc5de19c0b1edcf4cd053bd2fa9.json required fields: symbol, name, website

We have uploaed 2 files follow your guide at here https://github.com/BuildOnViction/tokens/pull/400/files
Please check it, is it ok?
Thanks

2023-11-13 23:42 UTC, bobcoin98 requested changes

2023-11-13 23:42 UTC, bobcoin98 commented on 0x567b1e373f7285e9a32f5eeb9305b6964b6a3532.json
> +        "email": "cryptocfb@gmail.com",
please use official project email
in your case, use mail ....@lottocfb.com

2023-11-14 01:25 UTC, cryptocfb commented on 0x567b1e373f7285e9a32f5eeb9305b6964b6a3532.json
> +        "email": "cryptocfb@gmail.com",
> please use official project email personal email is not accepted in your case, use mail [....@lottocfb.com](mailto:....@lottocfb.com)

Fuck you guys, you guys are so troublesome and a waste of users' time
1. In the instructions, is there any place where you must write that you must use an official email ending with lottocfb.com to be allowed? I don't see anywhere that says it's required to have an email extension like that to be allowed. Why can't I use gmail? Can you show me what conditions require that? It's not in the instructions, why ask now?
2. Support time is too long, it takes weeks for someone to respond after posting. We have created many tokens on the Tomochain platform and have never been required to use an official email to update. You can use gmail
3. You have few users and have a list of requirements that meet all the conditions, most of which are due to your errors (for example, the error of copying the smart contract on tomoscan automatically turns the letter b into a capital letter B, which also makes users make a mistake, even though it's your fault)
4. Please update the logo for us after we meet your basic requirements, and do not have any additional requests beyond the initial requirements.
5. Fuck you guys, fuck C98, fuck Tomochain for doing business like a dick

2023-11-14 01:48 UTC, cryptocfb commented
We have updated email official, please confirm is it ok? 
Update our logo soon for C98 wallet and Tomoscan, do not waste our time
Thanks

2023-11-14 03:16 UTC, bobcoin98 reviewed
This PR seems to be OK. Merging it now !
(This content is created via [Gittool](https://github.com/thanhnguyennguyen/lazy/tree/master/git)) 
 On behalf of [bobcoin98](https://github.com/bobcoin98)

2023-11-14 03:16 UTC, merged

2023-11-14 03:48 UTC, bobcoin98 commented
oops, wrong folder 
revert

2023-11-14 04:08 UTC, cryptocfb commented
> oops, wrong folder revert

is it done?

2023-11-14 04:10 UTC, bobcoin98 commented
done in my other commit
check here 
https://tomoscan.io/token/0x567b1e373f7285e9a32f5eeB9305b6964B6a3532

2023-11-14 06:14 UTC, cryptocfb commented
> done in my other commit
> check here
> https://tomoscan.io/token/0x567b1e373f7285e9a32f5eeB9305b6964B6a3532

But social link telegram, website, twitter have not update, why you ask us fill social link but you not update on tomoscan? Please update it

2023-11-14 06:38 UTC, cryptocfb commented
> done in my other commit
> check here
> https://tomoscan.io/token/0x567b1e373f7285e9a32f5eeB9305b6964B6a3532

Please update link telegram, twitter, .. on https://scan.tomochain.com/tokens/0x567b1e373f7285e9a32f5eeb9305b6964b6a3532

2023-11-14 10:31 UTC, cryptocfb commented
Why do you force us to update telegram social network links, emails (with official domain), and all other strict requirements, but after we follow those requirements, you don't update those links to Tomoscan? Why is it so funny? Are you kidding us? So why ask us to update? Why and WHY AND WHY?